import CTDLibSQLite
import XCTest
@testable import TelegramAllLib

/// Covers spec requirement "Reader obtains the SQLite key from the binlog"
/// (telegram-local-reader; PsychQuant/che-msg#58, task 3.1).
///
/// Fixtures come from a never-logged-in TDLib 1.8.60 directory generated by
/// Tools/reader-fixtures/generate.sh. The key is checked against an independent
/// oracle: SQLCipher must accept it and decrypt the fixture database.
final class LocalReaderBinlogTests: XCTestCase {
    private var fixtureDir: URL {
        Bundle.module.resourceURL!.appendingPathComponent("Fixtures/tdlib-1.8.60-test-dc")
    }

    private func path(_ name: String) -> String { fixtureDir.appendingPathComponent(name).path }

    /// Opens the fixture database with `key` through SQLCipher and returns its
    /// table names, or nil when SQLCipher rejects the key.
    private func tables(openedWith key: Data) -> [String]? {
        var db: OpaquePointer?
        guard tdsqlite3_open_v2(path("db.sqlite"), &db, TDSQLITE_OPEN_READONLY, nil) == TDSQLITE_OK else { return nil }
        defer { tdsqlite3_close(db) }
        let hex = key.map { String(format: "%02x", $0) }.joined()
        guard tdsqlite3_exec(db, "PRAGMA key = \"x'\(hex)'\"", nil, nil, nil) == TDSQLITE_OK else { return nil }
        var stmt: OpaquePointer?
        guard tdsqlite3_prepare_v2(db, "SELECT name FROM sqlite_master WHERE type = 'table'", -1, &stmt, nil) == TDSQLITE_OK else { return nil }
        defer { tdsqlite3_finalize(stmt) }
        var names: [String] = []
        while tdsqlite3_step(stmt) == TDSQLITE_ROW {
            if let text = tdsqlite3_column_text(stmt, 0) { names.append(String(cString: text)) }
        }
        return names
    }

    private func temporaryFile(_ bytes: [UInt8]) throws -> String {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("binlog-\(UUID().uuidString)")
        try Data(bytes).write(to: url)
        addTeardownBlock { try? FileManager.default.removeItem(at: url) }
        return url.path
    }

    // Scenario: Key extracted from a fixture binlog
    func testFixtureBinlogYieldsAKeyThatOpensTheFixtureDatabase() throws {
        let key = try TDLibBinlogReader.sqliteKey(fromBinlogAt: path("td.binlog"))
        XCTAssertEqual(key.count, 32)
        let names = try XCTUnwrap(tables(openedWith: key), "SQLCipher rejected the extracted key")
        for table in ["messages", "dialogs", "common"] {
            XCTAssertTrue(names.contains(table), "fixture database lacks \(table)")
        }
    }

    // Scenario: Truncated last event is skipped
    func testTruncatedLastEventIsSkippedAndTheKeyIsStillFound() throws {
        let key = try TDLibBinlogReader.sqliteKey(fromBinlogAt: path("td.binlog.truncated"))
        XCTAssertNotNil(tables(openedWith: key), "key from the truncated binlog does not open the database")
    }

    // Scenario: No sqlite_key in the binlog
    func testBinlogWithoutSqliteKeyThrowsKeyNotFound() {
        XCTAssertThrowsError(try TDLibBinlogReader.sqliteKey(fromBinlogAt: path("td.binlog.no-sqlite-key"))) {
            XCTAssertEqual($0 as? LocalReaderError, .keyNotFound)
        }
    }

    func testEmptyBinlogThrowsKeyNotFound() throws {
        let empty = try temporaryFile([])
        XCTAssertThrowsError(try TDLibBinlogReader.sqliteKey(fromBinlogAt: empty)) {
            XCTAssertEqual($0 as? LocalReaderError, .keyNotFound)
        }
    }

    /// A byte flipped inside the encryption event breaks its CRC, so the event is
    /// not used at all: the result is keyNotFound, not a wrong-key error from
    /// parsing the damaged salt.
    func testEventWithBadCRCIsNotUsed() throws {
        var bytes = [UInt8](try Data(contentsOf: fixtureDir.appendingPathComponent("td.binlog")))
        bytes[40] ^= 0xFF   // inside the first event's data (header is 28 bytes)
        let damaged = try temporaryFile(bytes)
        XCTAssertThrowsError(try TDLibBinlogReader.sqliteKey(fromBinlogAt: damaged)) {
            XCTAssertEqual($0 as? LocalReaderError, .keyNotFound)
        }
    }

    /// `BinlogKeyValue`: a rewrite replaces the entry with the same event id,
    /// an `Empty` rewrite erases it, and the last event wins.
    func testKeyValuesFollowRewritesAndErasures() throws {
        let dir = try LocalReaderFixture.copy(for: self, authorized: false)
        let binlog = dir.appendingPathComponent("td.binlog").path
        XCTAssertNil(try TDLibBinlogReader.keyValues(fromBinlogAt: binlog)["auth"])

        let ids = try LocalReaderFixture.appendBinlogEvents([.keyValue("auth", "ok")], to: binlog)
        XCTAssertEqual(try TDLibBinlogReader.keyValues(fromBinlogAt: binlog)["auth"], Array("ok".utf8))

        try LocalReaderFixture.appendBinlogEvents([.keyValue("auth", "logout", rewriting: ids[0])], to: binlog)
        XCTAssertEqual(try TDLibBinlogReader.keyValues(fromBinlogAt: binlog)["auth"], Array("logout".utf8))

        try LocalReaderFixture.appendBinlogEvents([.erase(ids[0])], to: binlog)
        let values = try TDLibBinlogReader.keyValues(fromBinlogAt: binlog)
        XCTAssertNil(values["auth"])
        XCTAssertEqual(values["sqlite_key"]?.count, 32, "erasing one entry must leave the others")
    }

    /// TDLib keeps one event id per key; should two ids ever hold the same
    /// key, the later event wins rather than whichever a hash table yields.
    func testLaterEventWinsWhenTwoIdsHoldTheSameKey() throws {
        let dir = try LocalReaderFixture.copy(for: self)   // auth = ok
        let binlog = dir.appendingPathComponent("td.binlog").path
        try LocalReaderFixture.appendBinlogEvents([.keyValue("auth", "logout")], to: binlog)   // a new id
        for _ in 0..<5 {
            XCTAssertEqual(try TDLibBinlogReader.keyValues(fromBinlogAt: binlog)["auth"], Array("logout".utf8))
        }
    }

    func testMissingFileThrowsBinlogUnreadable() {
        XCTAssertThrowsError(try TDLibBinlogReader.sqliteKey(fromBinlogAt: "/nonexistent/td.binlog")) {
            guard case .binlogUnreadable = $0 as? LocalReaderError else {
                return XCTFail("expected binlogUnreadable, got \($0)")
            }
        }
    }
}
